rclone-config: ENC[AES256_GCM,data:LXRgZ0VPf92oD/lO7PzGf7knMcrhDhPWwPnDy3K54lN1hEJFzdGUf9vFwPtBAZBpA3paT07Cmu0aDBKoGQAS1KdYqqidKLKh9H5W/UfBXHtjbBDYLQeQr1VgH4HNCrkbltNYSi28UkIJThmliFPt7HTMFlOGg1BvN2DfRa4q32hEFUKSobXiXue4/ut1axFwMpI+p/6XnrbcVeVBP7XunlzGHhN1Y0CV9zyL8awyV95x/yHKpm5ouIg0lj9xOuTri/B11WzsuAHYK84sDzPzWUbElYgEqIZb68L8p3+eCLG3qQqnwhmC3koVqGZoy+N7h8NWlzSoXnDGJ0sZ9jZVG5tuDPLGNIHWD2UrUGhAVZ12jEQLLV+D39sTeGdZT0YrDV3WQp1a9ltq516+3Tl1Jz+4U38ZGb2bnvEyVi7W7gKeHudUqik5ysMDM8iBQQDht+Nbd5tL420hNPV973Y9bvZm3PQMXslwDvfvVAPRBhEI9gFJTVuBtYOi8uOrC2M3TgOVIoG+uGWHuinHfzkcNhniImrhL0fKbiagP/s2s8fnIMMjRNFmfFIVbTWjIfqTq8j2vm1h/wsTFD/LX5/Dw84rO3CMHh/ufCNFKxYUnoTznLlll1qY6sIUzRhXADcXL8qnHWrlkxul/V6rbc9feIefNH/jreHFefDMfjtrzOwcMJvl5ASuPJQUm8AJTGDm33OiLynWDHbXFBoyPv0ge5w1nbG3Mbb9NcwIJ89JxrACfw7xSi56wJAOycCe2TyQu0VpSaR2vGLBfPSn3cGxQx6Vi6Sl4fM0vFxwEZv2nDs41nJJSRVKtgXgSBGH1AUxLTGBy7J3lnDqh/U5KpjMtCdV8PNwSHALOXiPaPmr6NRi8kYsG9vlYQxxdXuwoOrFnipXfJG+qCN7a1JlJqnPpwIRvv8mwPYXrSL1RuvXqmN1H5Wqfq5c4Bn3kp/L4QLNukH+KqiiAetB0yugI2upTofJ9H/3Qa4fL/uP04e+m8ThM7731sFuHNSrJDLjMCRNj6q6WbGYb6B340Fvz8QukqspehUTETcl7pQXyeFd7Es5mhnBN7KfH6Z2/xa0q6iC/AwX2eWup+bNKvdvLQe+oLuZB3HJG0QVFojHbjBiAmUTH6QBTxJ3gUypsSTYFcYbwk6pRMKDUbCi9cDBVqrPUWgCpH5fshwvK+jCbYhaNUEtakNwnYHNuWPeT1UDSrNaZ/u0bd4FJmUXaWapHQ8oMDfanRB0HEtx/IgZHzgI3ntg8jyZglEshHoN43FE1fv42KsVANc8qs7Vd1GeNbQzjtmwKv4emajlcXencnGdTlcZmss8BeR3hhQ19BFDX2vYPTMH+xbb1hj/QIr5WirR86VZ4zDFzKJcjYac9577rGI+sJTPO2y6hmuDJzJfwXOrIXYqrYYe1V1AE2HbQf4kFwlH/4tAH5TD8PIoK/gBxjBqQRJBUM7kxw3JBp7n8650f6PhHZb56R+kx0KPfoWhggUvB6ueaZVqqcEdkbNT3WiKCQJNmz+A2TwCcqyFGSIb+mMZBh8HkXPaEY9Y/HnlG+6w8jWl9SpCc0Mraxndyu/qqe6paTjfJv0hHliR0vi4mEh3IdnIbXiDiL6mArsuNQaPLGqWXjq/Zq+lNlaVmBBKbk9DGY7CqMBew05gtbYqGL/i5UTdvlAW/L/mGRDblUt9yKlv9m5o+8b3LI45q6+gqhfpqIo2u1KJDsUDq65RzVF63J9bXSqA6UVdtaq7bq1bZrjKQ292uBgmCq/+Bkr9SpVL0h4J,iv:WYE66dqOY1M3e7oiCbPGw9Uo6/uaR6vsCjjON06hILA=,tag:oAITnwQ0K5kVjucxy6xYHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VkFKZW9CWlJCUExHZUhW
            dnZZVHZMVi9EeHhpUFJmQ1FMSktSNU8zcTNjCmlLUmVzNGtxL2VaNFZWellkTEZB
            NDI3bVVoZ082WVNSNUZRaGdzbE93ckEKLS0tIGN5Wk5vWGVES0tEL1R3L3pkVHQ1
            MEU5VzdRR2xLeUZOc2I0QUNFKzRIM0EK4KgyIPxUhZYdbM4Aa+Ppho503VYPuQaS
            KsCfeVH3mLDb2GIHaHkyMyodYOmREdb5CQ+szdF0rElP12qq9ULKLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fgehy439lr05wwjqqju7zpx4s74m5deyr633mp9lawpcw4mvk95qkf9jey
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUUFpWnFtS1R5aDJUWUpF
            bGVJYkhIZlhhSkdoZng1TWRiSUdsOW1aQlY0CkVKOWsrSkdNdXBJbThuYjVZb2pr
            NUhBelZnYk91dk51cGozaTVlYzY3OVEKLS0tIFQ5ZXRJYld2Z2RZMUVoYzA4NDZS
            cXgxRHJtUWRoaU1kQ250ckQvTFlERWsK3Jjb1su9B7CFFI0KaAnlhD205sRxt4hh
            PshqFzjLrHUqiiZd7ECX+pbYedORaAjeP6AsdyyKvMD0tzmUPen1fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13pxcuqwr8fsthf3njt4y788e7356yqk88lllx57vatyf0dyjhvgst5tlfs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVVhDSUF2dzcwVjB3S3hX
            clpZa1oxeXVjV2dhaUpCWnlGT1Z0Q25IUkdBCldZblllS2krV1h1RURtVVFiT1Yx
            d054Zzl4anpFbStRbVpybVE2VjY2RVkKLS0tIEJBdlA1YnV5VUlGUFNPMEtZMEUr
            VnB1aVFWSG9pMWdzeUxYeWFSQTEzOGMK+2aSCPKD6UTzb+wLUmRFxtPps29oKUvu
            2aqIpd0pV45A1teDgWsXOLeVk0bLcPTZkR/OJiSag+GbEXRF9++hVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8lgsjwwllmf5743u33qj7mxq9pywdsrwtcumft39ujxa9uexdhskvek9f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjJyWjBkaFVVRVliRmEw
            MVQwVEw1UnVkRHYxbDBweFcvZ3E5R1hZZ3hzClVDREdqZU1xRE9saUc4Ym43Snln
            ZzlhRUVPajJzTm9NL1ZmTE5GR0N0QUkKLS0tIEx5dUhCRDg0OWpCZXJaWjk3WnNG
            TFdRS0wvUThPSVQ4bVVkV1YyOVUrNmsKy2/zjZmA6UBMNj9EJobzbm8hT5zV2BsM
            Iz7Nv4HnjTY5k/+VWEZNdACwO/49URBeg/PMICslCZutUWT7JJSSBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f3fgp6zwa47ayxuk5dgxv797uh3puz3u0784utg70tl4cy2ylf8q3zfx37
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUjdpQnBya0V3TkxOZWd5
            L0phYnVybWFOMjNNMVkvdG93aCsxc3ZFa20wCnN4dzV1aVVENzJKY3pLR2ZKdzRN
            WDZXMlJpVzhjRlR6dTI4czhFa3V0YUUKLS0tIE9YdmV6TU56TTNMMWU3TmwxaEtC
            R0Q5YkVHYlNWdzNNS2ZxeDBRdk40VjAKsT7cGp5mkLtfxxSYuJCH5fyHMmNZeUm4
            xz0sLRmbA976ZBXtt8vy4jSFCHP0CFySIXDM5k5QG9yyAbuXf5ELPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17l4lq89zpdyzlg37ktjtauyq60wnwuw0nj74rax67k9caldck9js63lleu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMlE5Z0t0WHVTZjlNZ2tq
            YzJOMEYxQ2JRVzNUTEZmbjlFOE0yeEpwLzJjCnIwd21UTWxMQVduWHM2RitkS0Zv
            VEF3OXNDR2dLTkV2RkRzZlZkY0ptc1kKLS0tIG9mK3hscHFRVE9yTm1PVFFSZ3Mx
            Q0ZyOWNCcXoxaVlsZEM5MWNYWVk2UHMK0cjWcCPdxIy+UTm6Sdu5hCWsieUQN3sq
            5Kim+yFueFrY7yXiBJB+4eSli/A0xDriraUqOFEXdVta2IU3nbBxqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16hf2jhj8g8lqmn76ax4janxjdgpmkzjjmrred349cyfl3hchxassjzppnc
    lastmodified: "2026-09-08T21:10:13Z"
    mac: ENC[AES256_GCM,data:BqaJMcf1f7fLoPdgeeL8m2AwGxY7tond8YoUiEo5fcRSVMX4WRA/ymsMoPUh8fbeMzdkrroBne/zutgSyjcc68egPTF7nMKKQTf3McQtdshSPEpw7dk87h0yqm9F9UN4c9ard5JI4H42drrzjPT3i36MSNajlqKr0f/3QMS4uoY=,iv:KUo9VawsPiW9x7bKD/4cPVcDLRx/zU0FsoJN8bP+yKw=,tag:umWP26k7xD/ApUc4+2kdTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
